var initConfig = {
    "type": "serial",
    "categoryField": "date",
    "dataDateFormat": "YYYY",
    "marginTop": 0,
    "plotAreaBorderColor": "#888888",
    "colors": [
        "#FF6600",
        "#FCD202",
        "#00d856",
        "#0D8ECF",
        "#2A0CD0",
        "#CD0D74",
        "#CC0000",
        "#00CC00",
        "#0000CC",
        "#DDDDDD",
        "#999999",
        "#333333",
        "#990000"
    ],
    "borderColor": "#B9B9B9",
    "color": "#141414",
    "fontFamily": "Montserrat",
    "fontSize": 10,
    "handDrawScatter": 0,
    "handDrawThickness": 0,
    // "balloon": {
    //     "adjustBorderColor": true,
    //     "color": "#ffffff",
    //     "cornerRadius": 5,
    //     "fillColor": "#000000"
    // },
    "categoryAxis": {
        // "autoRotateCount": 0,
        "gridPosition": "start",
        // "labelColorField": "",
        // "minPeriod": "YYYY",
        // "parseDates": false,//以日期值为X轴值
        // "position": "left",
        // "autoGridCount":false,
        "startOnAxis": true,
        "axisAlpha": 0.1,
        "axisColor": "#4B4F5E",
        "fillColor": "#4B4F5E",
        "firstDayOfWeek": 0,
        "gridAlpha": 0,
        "gridColor": "#4B4F5E",
        "labelOffset": 2,
        "minHorizontalGap": 68,
        "minorGridAlpha": 0,
        "minorGridEnabled": true,
        "minVerticalGap": 40,
        "labelRotation": 45,//文字45度倾斜
        // "equalSpacing": true,
        // "autoGridCount":false,
        // "gridCount":12,
        "titleFontSize": 2
    },
    "chartCursor": {
        // "enabled": true,
        // "fullWidth": true,
        // "oneBalloonOnly": true,
        "categoryBalloonDateFormat": "YYYY",
        "categoryBalloonEnabled": false,
        "cursorAlpha": 0.47,
        "cursorColor": "#191919",
        "valueLineAlpha": 0,
        "valueLineBalloonEnabled": false,
        "valueLineEnabled": true,
        "valueZoomable": true
    },
    "trendLines": [],
    "guides": [],
    "valueAxes": [],
    "allLabels": [],
    "balloon": {
        "borderColor": "#141414",
        "borderThickness": 1,
        "color": "#FFFFFF",
        "fillAlpha": 1,
        "fillColor": "#141414"
    },
    "legend": {
        "enabled": true,
        "useGraphSettings": true,
        "periodValueText": "[[value.sum]]",
    },
    "titles": [],
}